export const genderType = {
  0: "Faroeste",
  1: "Aventura",
  2: "Animação",
  3: "Comédia",
  4: "Crime",
  5: "Documentário",
  6: "Drama",
  7: "Família",
  8: "Fantasia",
  9: "História",
  10: "Terror",
  11: "Música",
  12: "Mistério",
  13: "Romance",
  14: "Ficção científica",
  15: "Cinema TV",
  16: "Thriller",
  17: "Guerra",
  18: "Ação",
};
